version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storyverse-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=storyverse
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    depends_on:
      - mysql
      - redis
    networks:
      - storyverse-network

  mysql:
    image: mysql:8.0
    container_name: storyverse-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: storyverse
      MYSQL_USER: storyverse_user
      MYSQL_PASSWORD: storyverse_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - storyverse-network

  redis:
    image: redis:7-alpine
    container_name: storyverse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - storyverse-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: storyverse-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - storyverse-network

volumes:
  mysql_data:
  redis_data:

networks:
  storyverse-network:
    driver: bridge